### PR TITLE
Fix string assert() calls which breaks PHP 7.2

### LINKED ISSUE #144: assert() funtion is deprecated in PHP 7.2
Sir, I try to open the editor but failed.
Here are my working environment and error msgs.
For your reference, thank you. :)
- Weathermap 1.0 dev
- Host platform (Win 7 x64, PHP 7.2, Cacti 1.1.38)
- Error Messages:

Deprecated: assert(): Calling assert() with a string argument is deprecated in C:\xampp\htdocs\cacti\plugins\weathermap\lib\Weathermap\Core\MapDataItem.php on line 141

Deprecated: assert(): Calling assert() with a string argument is deprecated in C:\xampp\htdocs\cacti\plugins\weathermap\lib\Weathermap\Core\MapDataItem.php on line 141

Deprecated: assert(): Calling assert() with a string argument is deprecated in C:\xampp\htdocs\cacti\plugins\weathermap\lib\Weathermap\Core\Map.php on line 215

Deprecated: assert(): Calling assert() with a string argument is deprecated in C:\xampp\htdocs\cacti\plugins\weathermap\lib\Weathermap\Core\Map.php on line 216

Deprecated: assert(): Calling assert() with a string argument is deprecated in C:\xampp\htdocs\cacti\plugins\weathermap\lib\Weathermap\Core\Map.php on line 217

Deprecated: assert(): Calling assert() with a string argument is deprecated in C:\xampp\htdocs\cacti\plugins\weathermap\lib\Weathermap\Core\Map.php on line 218

Deprecated: The each() function is deprecated. This message will be suppressed on further calls in C:\xampp\htdocs\cacti\plugins\weathermap\lib\Weathermap\Core\Map.php on line 345

### PR DESCRIPTION
**Pull request by netniV**
This PR corrects issues with the assert() function requiring the passed assertion to be a boolean.  

Closes #144

### CODE REVIEW

**Comment by netniV** [comment]
Those are issues with @howardjones's build scripts.  You should log them as a separate issue and point them at the travis build from this PR to demonstrate it.  I have never even got running with a vagrant system yet.

**Comment by peter279k** [comment]
@netniV, you're right. But the Travis CI build script should be fixed and this PR can check whether the `php-7.2` will be passed by `phpunit` test in Travis CI build.

**Comment by netniV** [comment]
This is @howardjones project and i'm just a contributor as I work on the cacti project this integrates with.

I won't personally be touching those as they are part of the repo's structure / design (imho) that @howardjones has settled upon and should be handled by him (unless he really wants me to).  

This PR was purely for the assert problem. I am sure he will appreciate what you've identified.

**Comment by peter279k** [comment]
@netniV, I know that. And I just notice that issue because the Travis CI build should be worked.
And it can let every oncoming PR be verified.
I know this issue I mention is not related to this PR, but I hope you can know what I concern.

Thanks.

**Comment by howardjones** [comment]
@peter279k Thanks for some insight on the TravisCI script! I actually
enabled both TravisCI and CircleCI at different times, but haven't had the
patience to make the dozens of trial & error commits so that the build
script actually builds :-)

The actual phpunit scripts do work though - I use those offline all the
time. Unfortunately, they partly use image comparisons to work, and the
output of GD is subtly different between different PHP versions.

**Comment by howardjones** [comment]
Travis actually fails on legit test failures now (including highlighting the issue in this PR, for PHP 7.2, which is nice!). The image comparison issue I mentioned means that a bunch of tests still fail though. I'll need to generate references images for each version before that can be fixed.

**Pull request merged**
